public Class A0
{

public Account createAccount(String name)
{
//Developer 1 ADO Board User Story
//Testing
Account a01= new Account();
a01.Name = name;
return a01;
//Test the VS code IDE with deplying to org and committing
}
    
public static void anotherMethod() 
{
//testing ar 31176
//Developer 2 JIRA User Story
System.debug('Another method called!');
// Add more code for the new method if needed
//modified for ez commit
//modified for a commit template
}
}// modified by ramya for ez-commit