public class AccountAnalyzer {
    public static Map<String, Integer> analyzeAccountTypes(List<Account> accounts) {
        // Logic to analyze account types and count occurrences
        return new Map<String, Integer>();
        // Testing CI jobs
        //Testing Commit
        // testing123
        //Testing the Piipeline for Guardian Industries
        //Testing the Pipeline for Guardian Industries
        //Testing the Pipeline for Guardian Industries - Test-3
        //RL-Test
    }
}