public class AccountManager1 {
    public static void createAccount(String accountName) {
        // Implementation to create an account
    }
    public static void test(String accountName) {
        // Testing merge conflict
    }
    public static void deleteAccount(String accountId, String newAccountName) {
        // Implementation to update an account
    }
    public static void updateAccount(String accountId, String newAccountName) {
        // Implementation to update an account
        //Merge conflict Test
    }
}