public class autoPopulate {
    // Method to convert meters to centimeters
    public static Decimal convertMetersToCentimeters(Decimal meters) {
        return meters * 100;
    }

    // Method to convert meters to millimeters
    public static Decimal convertMetersToMillimeters(Decimal meters) {
        return meters * 1000;
    }
        public static Decimal convertMetersToMillimeterss(Decimal meters) {
        return meters * 1000;
    }
}