public class MathOperations {
    
  public static void addition(integer firstNumber, integer secondNumber)
  {
     system.debug('Addition result is :'+ (firstNumber + secondNumber)); 
  }
  public static void subtraction(integer firstNumber, integer secondNumber)
  {
     system.debug('subtraction result is :'+ (firstNumber - secondNumber)); 
  }
  public static void multiply(integer firstNumber, integer secondNumber, integer thirdNumber)
  {
     system.debug('multiplication result is :'+ (firstNumber * secondNumber * thirdNumber)); 
  }
  public static void division(integer firstNumber, integer secondNumber)
  {
      system.debug('division result is :'+ (firstNumber/secondNumber));
  }
}